# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-request-limit: 25
    schedule:
      interval: "weekly"
    groups:
      golang-org:
        applies-to: "version-updates"
        patterns:
          - "golang.org"
